/* config-keepassx.h. Generated by cmake from config-keepassx.h.cmake */

#ifndef KEEPASSX_CONFIG_KEEPASSX_H
#define KEEPASSX_CONFIG_KEEPASSX_H

#define KEEPASSX_VERSION "2.0.3"

#define KEEPASSX_SOURCE_DIR ""
#define KEEPASSX_BINARY_DIR ""

#define KEEPASSX_PREFIX_DIR ""
#define KEEPASSX_PLUGIN_DIR ""
#define KEEPASSX_DATA_DIR ""

#define HAVE_PR_SET_DUMPABLE 1
#define HAVE_RLIMIT_CORE 1
/* #undef HAVE_PT_DENY_ATTACH */

#endif // KEEPASSX_CONFIG_KEEPASSX_H
